channels:
    - conda-forge
    - nodefaults
dependencies:
    - r-base
    - r-renv
    - r-quarto
    # This lists fairly excessive
    # dependencies that may be used to build
    # R packages from source within this environment.
    - binutils
    - glib
    - gettext
    - gxx_linux-64
    - gcc_linux-64
    - make
    - pkg-config
    - libgomp
    - zlib
    - libblas
    - liblapack
    - autoconf
    - glpk
    - gmp
    # r xml2: https://github.com/r-lib/xml2/issues/418
    - libxml2==2.11.6
    - gfortran
    - openmp
    - gettext-tools
    - libiconv
    - pcre2
    - libint
    - packaging
    - setuptools
    - cxx-compiler
