name: quarto
description: Render quarto markdown documents
authors:
  -Vito Zanotelli
input:
  - script: > 
      Quarto script to render (.qmd).
      - The script must follow the following rules:
        - If parameters are used (extra arguments in `input`, `output`, `params`)
          they must be defined in the quarto header as params: https://quarto.org/docs/computations/parameters.html#knitr
        - All dependencies used in the script must either be:
          - installed in the `renv` declared as `input.renv` (see `input.renv` documentation)
          - installed in the conda environment used to run this wrapper. If this is customized, use
            the `conda: ` parameter to overwrite the default conda environment.
  - renv: >
      Optional:
      Path a folder containing restored `renv` environment or a file within
      (eg `.Rprofile`, `renv.lock`). If this is used the `renv` must
      contain a full `quarto` installation.
      Note that the R version depends on the conda environment used in the wrapper.
      If this needs to be changed, change the `conda:` parameter to point to an
      appropriate conda environment.
      Default: the project root directory
  - `<additional_inputs>`: >
      Additional input files. These the paths will be passed as `params:<additional_inputs>` to the quarto script
      and need to be defined in the quarto header as params: https://quarto.org/docs/computations/parameters.html#knitr
output:
  - report: >
      Optional:
      Path to the rendered report. The file extension will be used to determine the output format (eg `report.html`, `report.pdf`)
      If not provided, the report will be rendered in a temporary directory and no output will be returned.
  - `<additional_outputs>: >
      Additional output files. These the paths will be passed as `params:<additional_outputs>` to the quarto script
      and need to be defined in the quarto header as params: https://quarto.org/docs/computations/parameters.html#knitr
params:
  - `<additional_outputs>: >
      Additional parameters to be passed to the quarto script. These the paths will be passed as `params:<additional_outputs>` to the quarto script
      and need to be defined in the quarto header as params: https://quarto.org/docs/computations/parameters.html#knitr
      If wildcards should be passed to the `quarto` script, use a function to pass it in params:
      `params: project: lambda wc: wc.project`
notes: |
  This wrapper runs 