rule all:
    input:
        "a.reheader.bcf",
        "a.reheader_map.bcf"

rule bcftools_reheader:
    input:
        vcf="a.bcf",
        ## new header, can be omitted if "samples" is set
        header="header.txt",
        ## file containing new sample names, can be omitted if "header" is set
        samples="samples.tsv",
    output:
        "a.reheader.bcf",
    log:
        "reheader.log",
    params:
        uncompressed_bcf=False,
        extra="",  # optional parameters for bcftools reheader
        view_extra="",  # optional parameters for bcftools view
    threads: 2
    wrapper:
        "master/bio/bcftools/reheader"

rule bcftools_reheader_map:
    input:
        vcf="a.bcf",
        ## file containing a whitespace separated mapping of old to new sample names
        samples="samples_map.tsv",
    output:
        "a.reheader_map.bcf",
    log:
        "reheader_map.log",
    params:
        uncompressed_bcf=False,
        extra="",  # optional parameters for bcftools reheader
        view_extra="",  # optional parameters for bcftools view
    threads: 2
    wrapper:
        "master/bio/bcftools/reheader"
